language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  - CODECEPTION_VERSION="2.0" GUZZLE="4.*"
  - CODECEPTION_VERSION="2.1" GUZZLE="5.*"

before_script:
  - composer install -n --prefer-dist --dev
  - composer require guzzlehttp/guzzle:${GUZZLE}
  - composer require codeception/codeception:${CODECEPTION_VERSION}

script:
  - bin/codecept build
  - bin/codecept run
